import test from 'node:test';import assert from 'node:assert/strict';import {newGame,transition} from './game.js';import {countries} from './countries.js';
function answer(s,correct=true){return transition(s,{type:'answer',id:correct?s.deck[s.turn].country.id:'wrong'});}
function next(s){return transition(s,{type:'continue'});}
function reachDecision(){let s=transition(newGame(['A','B'],2),{type:'ready'});s=next(answer(s));return next(answer(s));}
test('unique countries, four valid unique options, equal turns',()=>{for(const rounds of [2,4,6]){const s=newGame([' A ',''],rounds);assert.equal(s.deck.length,rounds*2);assert.equal(new Set(s.deck.map(x=>x.country.id)).size,rounds*2);assert.deepEqual(s.names,['A','Explorer 2']);for(const q of s.deck){assert.equal(new Set(q.options.map(x=>x.id)).size,4);assert(q.options.some(x=>x.id===q.country.id));}}});
test('bank, handoff, no duplicate settlement',()=>{let s=reachDecision();assert.equal(s.pot,150);s=transition(s,{type:'bank'});s=transition(s,{type:'finish'});assert.deepEqual(s.scores,[150,0]);assert.equal(s.turn,1);assert.equal(s.stage,'handoff');assert.deepEqual(transition(s,{type:'finish'}),s);});
test('flag success awards 250 and wrong flag loses only current pot',()=>{for(const correct of [true,false]){let s=reachDecision();s.scores=[75,0];s=transition(s,{type:'risk'});s=next(answer(s,correct));s=transition(s,{type:'finish'});assert.equal(s.scores[0],correct?325:75);}});
test('wrong answers teach, repeat answers do not score twice',()=>{let s=transition(newGame(['A','B'],2),{type:'ready'});s=answer(s,false);assert.equal(s.pot,0);assert.equal(s.feedback.answer,s.deck[0].country.name);assert.deepEqual(answer(s,true),s);});
test('full match ends after equal turns and banks once',()=>{let s=newGame(['A','B'],2);for(let i=0;i<4;i++){s=transition(s,{type:'ready'});s=next(answer(s));s=next(answer(s));s=transition(s,{type:'bank'});s=transition(s,{type:'finish'});}assert.equal(s.stage,'results');assert.deepEqual(s.scores,[300,300]);});
test('starter data contains unique identifiers and capitals',()=>{assert.equal(countries.length,12);assert.equal(new Set(countries.map(c=>c.id)).size,12);assert.equal(new Set(countries.map(c=>c.capital)).size,12);for(const c of countries)assert.equal(c.clues.length,3);});
