import React,{useReducer,useState,useEffect,useRef,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {newGame,transition,answerStatus,winners} from './game.js';
import {countries} from './countries.js';
import {flagUrl} from './flags.js';
const WorldMap=lazy(()=>import('./WorldMap.jsx'));
import './style.css';
const avatars=['☀','☾','✦','❀','◆','♧','☁','⚡'];
function App(){
 const [names,setNames]=useState(['Explorer 1','Explorer 2']);const [rounds,setRounds]=useState(6);const [difficulty,setDifficulty]=useState('classic');const [s,dispatch]=useReducer((state,action)=>action.type==='start'?newGame(action.names,action.rounds,action.difficulty):action.type==='reset'?null:transition(state,action),null);const heading=useRef(null);
 useEffect(()=>{heading.current?.focus()},[s?.stage,s?.turn]);
 const c=s?.deck[s.turn]?.country;const player=s?s.turn%s.names.length:0;const leaders=s?winners(s):[];const question=['country','capital','flag'].includes(s?.stage);
 return <div className="app"><header><a className="brand" href="./"><span>✳</span> WORLD QUEST</a><span className="edition">THE FAMILY EXPLORER CLUB</span></header><main>
 {!s?<section className="start"><div className="intro"><span className="eyebrow">2–8 PLAYERS · ONE BIG WORLD</span><h1>Your next stop?<br/><em>Somewhere amazing.</em></h1><p>Follow the clues. Find the country. Take a chance.<br/>A little friendly competition, a world of discoveries.</p><div className="postcards" aria-label="Sample travel clues"><div>🗻<small>Landmarks</small></div><div>🦁<small>Wildlife</small></div><div>🥐<small>Culture</small></div></div><span className="stamp">{countries.length} COUNTRIES · 6 CONTINENTS</span></div><form className="setup" onSubmit={e=>{e.preventDefault();dispatch({type:'start',names,rounds,difficulty})}}><span className="eyebrow">YOUR BOARDING PASS</span><h2>Who’s exploring?</h2><p className="small" aria-live="polite">{names.length} of 8 players · Everyone gets equal turns.</p><div className="player-list">{names.map((name,i)=><div className="player-row" key={i}><label>Player {i+1}<input maxLength={24} value={name} onChange={e=>setNames(names.map((n,j)=>j===i?e.target.value:n))}/></label><button className="remove-player" type="button" disabled={names.length<=2} aria-label={`Remove player ${i+1}${name?`: ${name}`:''}`} onClick={()=>setNames(current=>current.length>2?current.filter((_,j)=>j!==i):current)}>Remove</button></div>)}</div><button className="secondary add-player" type="button" disabled={names.length>=8} onClick={()=>setNames(current=>current.length<8?[...current,'']:current)}>{names.length>=8?'Maximum 8 players':'+ Add player'}</button><label>Trip length<select value={rounds} onChange={e=>setRounds(Number(e.target.value))}><option value={6}>Grand Adventure · 6 turns each</option><option value={4}>World tour · 4 turns each</option><option value={2}>Quick trip · 2 turns each</option></select></label><fieldset className="difficulty"><legend>Choose your challenge</legend><label className={difficulty==='classic'?'chosen':''}><input type="radio" name="difficulty" value="classic" checked={difficulty==='classic'} onChange={()=>setDifficulty('classic')}/><span><strong>Clue Explorer</strong><small>Three clues · 4 choices</small></span></label><label className={difficulty==='map'?'chosen':''}><input type="radio" name="difficulty" value="map" checked={difficulty==='map'} onChange={()=>setDifficulty('map')}/><span><strong>Map Explorer <b>HARD</b></strong><small>Animated border map · 8 choices</small></span></label></fieldset><button className="primary">Let’s explore →</button><p className="small">Country +100 · Capital +50<br/>Bank your points, or risk this turn for a +100 flag bonus. A wrong flag loses this turn’s points.</p></form></section>:<>
 <div className="scoreboard">{s.names.map((n,i)=><div key={i} className={'score '+(player===i&&s.stage!=='results'?'active':'')}><span>{avatars[i]} {n}</span><strong>{s.scores[i]} <small>pts</small></strong></div>)}</div>
 <div className="tripline"><span>{s.stage==='results'?'JOURNEY COMPLETE':`ROUND ${Math.floor(s.turn/s.names.length)+1} OF ${s.rounds}`}</span><div className="progress">{s.deck.map((_,i)=><i key={i} className={i<s.turn?'done':i===s.turn?'current':''}/>)}</div><button className="text" onClick={()=>{if(window.confirm('End this trip and return to setup?'))dispatch({type:'reset'})}}>New trip</button></div>
 <section className={'game '+(s.difficulty==='map'?'map-game':'')} aria-label="Game board">
 {s.stage==='handoff'?<div className="center"><span className="big-symbol">{avatars[player]}</span><span className="eyebrow">PASS THE DEVICE</span><h1 ref={heading} tabIndex={-1}>{s.names[player]},<br/>you’re up!</h1><p>A new country is waiting. Ready to discover it?</p><button className="primary" onClick={()=>dispatch({type:'ready'})}>I’m ready →</button></div>:s.stage==='results'?<div className="center"><span className="big-symbol">🏆</span><span className="eyebrow">WHAT A TRIP</span><h1 ref={heading} tabIndex={-1}>{leaders.length===1?`${leaders[0].name} wins!`:'A shared victory!'}</h1><p>{leaders.length>1?`${leaders.map(p=>p.name).join(' & ')} tie with ${leaders[0].score} points each. `:''}You explored {s.deck.length} countries together.</p><div className="passport">{s.deck.map(({country})=><span key={country.id}><img src={flagUrl(country.id)} alt=""/>{country.name}</span>)}</div><button className="primary" onClick={()=>dispatch({type:'start',names:s.names,rounds:s.rounds,difficulty:s.difficulty})}>Play again →</button></div>:<>
 <div className="clue-panel"><span className="eyebrow">{s.stage==='country'?'DESTINATION UNKNOWN':c.region.toUpperCase()}</span><h2>{s.stage==='country'?(s.difficulty==='map'?'Let the borders guide you.':'Three little clues.'):c.name}</h2>{s.difficulty==='map'&&s.stage==='country'?<><Suspense fallback={<div className="map-loading" role="status">Preparing your flight…</div>}><WorldMap key={c.id} countryId={c.id}/></Suspense>{s.feedback&&<div className="map-reveal-clues">{c.clues.map(([icon,label])=><p key={label}>{icon} {label}</p>)}</div>}</>:<><div className="clues">{c.clues.map(([icon,label])=><div className="clue" key={label}><span aria-hidden="true">{icon}</span><strong>{label}</strong></div>)}</div><p className="clue-caption">Three clues to connect with this country.</p></>}</div>
 <div className="challenge"><div className="challenge-meta"><span>{s.names[player]}’s turn</span><b>{s.pot} pts this turn</b></div>
 <h2 ref={heading} tabIndex={-1}>{s.stage==='country'?'Where in the world?':s.stage==='capital'?(c.capitalPrompt||`What’s the capital of ${c.name}?`):s.stage==='flag'?`Which flag belongs to ${c.name}?`:s.stage==='decision'?'Feeling adventurous?':'A new stamp in your passport.'}</h2>
 {question&&<><p>{s.stage==='country'?(s.difficulty==='map'?'Guess the country outlined in orange. Eight choices, no labels.':'Pick the country that connects these clues.'):s.stage==='capital'?'Another discovery. Another 50 points.':'Get it right: +100. Get it wrong: lose this turn’s points.'}</p><div className="answers">{s.deck[s.turn].options.map((o,i)=><button key={o.id} disabled={!!s.feedback} className={'answer '+answerStatus(s,o.id)} onClick={()=>dispatch({type:'answer',id:o.id})}><span className="letter">{s.feedback&&o.id===c.id?'✓':s.feedback&&o.id===s.feedback.selectedId?'✕':String.fromCharCode(65+i)}</span>{s.stage==='flag'?<img className="flag" src={flagUrl(o.id)} alt={`Flag option ${String.fromCharCode(65+i)}`}/>:s.stage==='country'?o.name:o.capital}</button>)}</div>{s.feedback&&<div className="feedback" role="status"><strong>{s.feedback.correct?'✓ Correct!':'✕ Not quite. Correct answer:'} {s.feedback.answer}</strong><p>{s.stage==='flag'&&!s.feedback.correct?'This turn earns 0 points. Your earlier points are safe.':s.stage==='country'?c.fact:(c.capitalNote||`${c.name} · ${c.capital}`)}</p><button className="primary" onClick={()=>dispatch({type:'continue'})}>Continue →</button></div>}</>}
 {s.stage==='decision'&&<><p>You’ve collected <strong>{s.pot} points</strong>. Keep them, or try a flag challenge for 100 more.</p><div className="decision"><button className="primary" onClick={()=>dispatch({type:'bank'})}>Bank {s.pot} points</button><button className="secondary" onClick={()=>dispatch({type:'risk'})}>Risk it · flag bonus +100</button></div><p className="small">A wrong flag loses only this turn’s points. Previously banked points are always safe.</p></>}
 {s.stage==='recap'&&<><div className="reveal"><img src={flagUrl(c.id)} alt={`Flag of ${c.name}`}/><div><strong>{c.name}</strong><p>{c.id==='nr'||c.id==='ps'?'Government centre':'Capital'}: {c.capital}</p></div></div><p>{c.fact}</p>{c.capitalNote&&<p className="small">{c.capitalNote}</p>}<p className="earned">+{s.pot} points earned</p><button className="primary" onClick={()=>dispatch({type:'finish'})}>{s.turn===s.deck.length-1?'See the results':'Bank & pass the device'} →</button></>}
 </div></>}
 </section></>}
 </main><footer><span>A little curiosity goes a long way.</span><span>Shared device · No timer · Just play</span><a href={`${import.meta.env.BASE_URL}data-sources.html`} target="_blank" rel="noreferrer">Country data & map credits</a></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
